### ISSUE TITLE
Supported Firebase C++ SDK version, Qt version and an Example

### ISSUE THREAD

**Issue by shujaatak** [ceciletti/firebase-qt#1]
This repository looks promising!
Can you please mention with which version of **Firebase C++ SDK** and **Qt** you have tested this repository also an **example** with this repository would be much helpful.
By the way, I am learning to use latest Firebase SDK with Qt5.14.2 and I found your this repository.

Kindest regards!

**Comment by dantti** [comment]
hi, I've been using Qt 5.12 and lastestest FB C++ SDK

**Comment by shujaatak** [comment]
A simple get-started example or doc or a paragraph would be much appreciated.
