### ISSUE TITLE
Not receiving message on foreground app

### ISSUE THREAD

**Issue by LucaVs** [ceciletti/firebase-qt#2]
Hi,
I'm using FirebaseQt to get firebase push notification on my Qt Android app.
After configuring Android App and firebase console I 'm using this class:

```
Firebase::Firebase(QObject *parent)
    : QObject{parent}
{
#if defined(Q_OS_ANDROID) || defined(Q_OS_IOS)
    auto firebase = new FirebaseQtApp(this);

    auto messaging = new FirebaseQtMessaging(firebase);
    connect(messaging, &FirebaseQtMessaging::tokenReceived, this, &Firebase::tokenReceived, Qt::QueuedConnection);
    connect(messaging, &FirebaseQtMessaging::messageReceived, this, &Firebase::messageReceived, Qt::QueuedConnection);

    firebase->initialize();
#endif
}

void Firebase::tokenReceived(const QByteArray &token)
{
    qDebug() << "Got Firebase Messaging token" << token;
    _token = QString::fromLatin1(token);
    qDebug() << _token;
    Q_EMIT tokenChanged();
}

void Firebase::messageReceived(const QMap<QString, QString> &data)
{
    qDebug() << "Got a Push Notification when the app is running" << data;
}

```

I can get the token on **tokenReceived** and I can use that token on firebase console to send a test message to my device.

The problem is that I can see the notification while app is closed but it never call **messageReceived** when app is open.

Am I missing anything?

**Comment by dantti** [comment]
Not that I recall, it used to work for me

**Comment by LucaVs** [comment]
It seems it's related to firebase SDK version.
Using https://dl.google.com/firebase/sdk/cpp/firebase_cpp_sdk_5.7.0.zip resolved the issue.

**Comment by dantti** [comment]
Right, I had some issues when trying to use newer versions, if you manage to fix please let me know or even better do a PR :)

**Comment by LucaVs** [comment]
At the moment have not much time to fix. 
I'll use SDK 5.7.0.

Thanks for support.
